name: Build OrangePi Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          docker system prune -af

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y \
            git curl wget docker.io qemu-user-static

      - name: Fix config
        run: |
          sed -i 's/orangepi-4pro/orangepi4pro/g' userpatches/config-example.conf || true

      - name: Build image
        run: |
          chmod +x build.sh

          sudo ./build.sh \
            BOARD=orangepi4pro \
            BRANCH=current \
            RELEASE=jammy


      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: orangepi-image
          path: output/images/*
