name: Build OrangePi Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          docker system prune -af

      - name: Install deps
        run: |
          sudo apt update
          sudo apt install -y \
            git curl wget docker.io qemu-user-static

      - name: Build image
        run: |
          chmod +x build.sh

          ./compile.sh \
          BOARD=orangepi4pro
          BOARD_NAME="Orange Pi 4 Pro"
          BOARDFAMILY="sun60iw2"
          BOOTCONFIG="sun60iw2p1_t736_defconfig"
          BOOT_LOGO="desktop"
          BOOT_FDT_FILE="allwinner/sun60i-a733-orangepi-4-pro.dtb"
          MODULES="aic8800_fdrv aic8800_btlpm pvrsrvkm"
          KERNEL_TARGET="current"
          DISTRIB_TYPE_CURRENT="jammy"
          DISTRIB_TYPE_LEGACY="jammy"
          SKIP_BOOTSPLASH="yes"
          REVISION="1.0.8"


      - name: Upload images
        uses: actions/upload-artifact@v4
        with:
          name: orangepi-image
          path: output/images/*
